# Render Deploy Configuration
RENDER=true
NODE_ENV=production

# Build Command - Otimizado para Render (sem testes)
npm install && npx prisma generate && npm run build

# Start Command  
npm run deploy

# Node Version
NODE_VERSION=18.18.0